name: example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2  # 환경 변수 관리 패키지
  photo_view: ^0.15.0  # 이미지 확대/축소를 위한 패키지, 최신 버전으로 업데이트
  cupertino_icons: ^1.0.2  # iOS 스타일의 아이콘을 위한 패키지
  flutter_gemini:
    path: ../  # flutter_gemini 패키지 경로, 올바른지 확인 필요
  lottie: ^2.7.0  # 애니메이션 로티 파일을 처리하는 패키지
  flutter_markdown: ^0.6.18+2  # 마크다운 렌더링을 위한 패키지
  image_picker: ^1.0.5  # 이미지 선택을 위한 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # 코드 린팅을 위한 패키지

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/  # 로티 애니메이션 파일이 위치한 폴더
    - .env

  # 여기에 추가적인 이미지, 글꼴 또는 기타 리소스를 추가할 수 있습니다.
