name: my_flutter_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  photo_view: ^0.15.0
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_layout_grid: ^2.0.4
  flutter_math_fork: ^0.7.2
  flutter_markdown: ^0.7.3+1  # Ensure this line is present
  flutter_gemini: ^2.0.5
  csv: ^5.0.0 # 원하는 버전으로 지정
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
